'use client';
import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext(null);

const translations = {
  en: {
    // Navbar
    login: 'Log In',
    getStarted: 'Get Started',

    // Hero
    badge: 'Industry 4.0 Platform',
    heroTitle1: 'Powering Industries',
    heroTitle2: 'with Premium Coir',
    heroTitle3: 'Sustainable',
    heroTitle4: 'Fiber Solutions',
    heroDesc: 'An all-in-one coir manufacturing and supply chain platform — monitor production in real time, manage inventory seamlessly, and gain intelligent supply chain insights.',
    viewInventory: 'View Inventory',
    tonsMonth: 'Tons / Month',
    countries: 'Countries',
    qualityRate: 'Quality Rate',
    scrollExplore: 'Scroll to explore',

    // Stats
    statsTitle: 'Numbers That Speak',
    statsSubtitle: 'Our production metrics tell the story of excellence',
    dailyOutput: 'Daily Output',
    clientsServed: 'Clients Served',
    exportCountries: 'Export Countries',
    yearsExperience: 'Years Experience',
    ourImpact: 'Our Impact',
    performance: 'Performance',
    industryLeading: 'Industry-Leading',
    statsDesc: 'Delivering premium coir products globally with unmatched quality, consistency, and reliability',
    tonsProducedMonthly: 'Tons Produced Monthly',
    highCapacityMfg: 'High-capacity industrial manufacturing',
    globalCoverage: 'Global supply chain coverage',
    activeClients: 'Active Clients',
    trustedPartnerships: 'Trusted business partnerships',
    qualityAssurance: 'Quality Assurance',
    isoCertified: 'ISO-certified inspection process',

    // Manufacturing
    mfgTitle: 'Manufacturing Process',
    mfgSubtitle: 'From raw coconut husk to premium finished products',

    // CTA
    ctaTitle: 'Ready to Transform Your Supply Chain?',
    ctaDesc: 'Join hundreds of businesses that trust Smart Coir for premium quality coir products and efficient supply chain management.',
    ctaButton: 'Start Your Journey',
    whyChooseUs: 'Why Choose Us',
    futureCoirTitle: 'The Future of',
    coirMfg: 'Coir Manufacturing',
    ctaLeftDesc: 'We combine traditional craftsmanship with cutting-edge technology to deliver premium coir products. Our smart platform gives you complete visibility over the entire manufacturing and supply chain process.',
    startFreeTrial: 'Start Free Trial',
    scheduleDemo: 'Schedule Demo',
    feat1Title: 'Real-Time Tracking',
    feat1Desc: 'Monitor production, inventory, and deliveries with live dashboards and instant alerts.',
    feat2Title: 'AI-Powered Insights',
    feat2Desc: 'Smart analytics predict demand, optimize stock levels, and maximize revenue growth.',
    feat3Title: 'Supply Chain Control',
    feat3Desc: 'End-to-end visibility from coconut husk collection to global product delivery.',
    feat4Title: 'Quality Assurance',
    feat4Desc: 'ISO-certified testing at every stage ensures export-ready, premium products.',

    // Footer
    footerDesc: 'Premium coir manufacturing and supply chain management platform. Transforming coconut fiber into sustainable industrial products.',
    quickLinks: 'Quick Links',
    home: 'Home',
    about: 'About',
    contact: 'Contact',
    contactInfo: 'Contact Info',
    rights: 'All rights reserved.',
    products: 'Products',
    company: 'Company',
    platform: 'Platform',
    support: 'Support',
    coirRope: 'Coir Rope',
    coirYarn: 'Coir Yarn',
    fiberBundles: 'Fiber Bundles',
    rawFiber: 'Raw Fiber',
    aboutUs: 'About Us',
    manufacturing: 'Manufacturing',
    qualityStandards: 'Quality Standards',
    careers: 'Careers',
    inventorySystem: 'Inventory System',
    orderTracking: 'Order Tracking',
    contactUs: 'Contact Us',
    documentation: 'Documentation',
    faq: 'FAQ',
    liveChat: 'Live Chat',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',

    // Language names
    langEn: 'English',
    langTa: 'தமிழ்',
    langHi: 'हिन्दी',

    // Auth
    signInPortal: 'Sign In Portal',
    selectRole: 'Please select your portal role to continue',
    clientPortal: 'Client Portal',
    adminPanel: 'Admin Panel',
    emailAddress: 'Email Address',
    emailPlaceholder: 'name@company.com',
    password: 'Password',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'Forgot Password?',
    signInBtn: 'Sign In',
    authenticating: 'Authenticating...',
    dontHaveAccount: "Don't have an account?",
    createOneNow: 'Create one now',
    createAccountPortal: 'Create Client Account',
    alreadyHaveAccount: 'Already have an account?',
    backToLogin: 'Log In here',
    registerBtn: 'Register Company',
    registering: 'Registering...',
    fullName: 'Full Name',
    companyName: 'Company Name',
    companyAddress: 'Company Address',
    phone: 'Phone Number',
    step: 'Step',
    personalDetails: 'Personal Details',
    companyDetails: 'Company Details',
    continue: 'Continue',
    buyCoir: 'Buy Coir Products',
    back: 'Back',

    // Sidebar & Menus
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    orders: 'My Orders',
    chat: 'Support Chat',
    profile: 'Profile Settings',
    contactAdmin: 'Contact Admin',
    scanner: 'QR Scanner',
    workers: 'Workers Directory',
    suppliers: 'Suppliers Directory',
    adminHome: 'Admin Home',
    manageProducts: 'Manage Products',
    clientOrders: 'Client Orders',
    liveSupport: 'Live Support',
    systemStatus: 'Live Server',
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications yet',
    signOut: 'Sign Out',

    // Client Dashboard
    welcome: 'Welcome',
    repOf: 'Representative of',
    manageCoirOrders: 'Manage your inventory orders and track shipments.',
    browseCatalog: 'Browse Catalog',
    orderHistory: 'Order History',
    totalOrdersPlaced: 'Total Orders Placed',
    activeShipments: 'Active Shipments',
    completedDeliveries: 'Completed Deliveries',
    totalInvestments: 'Total Investments',
    recentOrders: 'Recent Orders',
    noOrders: 'No orders found',
    viewAllOrders: 'View All Orders',
    orderId: 'Order ID',
    date: 'Date',
    total: 'Total',
    status: 'Status',
    actions: 'Actions',
    track: 'Track',

    // Client Inventory
    availableProducts: 'Available Coir Products',
    searchPlaceholder: 'Search coir products...',
    stock: 'Stock',
    price: 'Price',
    viewDetails: 'View Details',
    categories: 'Categories',

    // Client Products Detail
    productDetails: 'Product Details',
    specifications: 'Specifications',
    pricePerTon: 'Price per Ton',
    availableQty: 'Available Quantity',
    backToInventory: 'Back to Inventory',
    placeOrder: 'Place Order',
    orderEstimator: 'Order Estimator & Spec Configurator',
    fiberGrade: 'Fiber Grade',
    moistureLimit: 'Moisture Limit',
    baleWeight: 'Bale Weight',
    quantityTons: 'Quantity (Tons)',
    estimatedPrice: 'Estimated Price',
    taxFees: 'Tax & Shipping Fees',
    grandTotal: 'Grand Total',
    submittingOrder: 'Submitting Order...',
    confirmOrder: 'Confirm Order',
    estimatedDelivery: 'Estimated Delivery',

    // Client Profile
    companyProfileSettings: 'Company Profile Settings',
    updateCompanyDetails: 'Update your company information and delivery addresses.',
    companyDetails: 'Company Details',
    saveChanges: 'Save Changes',
    saving: 'Saving...',

    // Client Contact
    contactOffice: 'Contact Office',
    sendInquiry: 'Send Support Inquiry',
    subject: 'Subject',
    message: 'Message',
    sendBtn: 'Send Message',
    sending: 'Sending...',
    contactDesc: 'Get in touch with our team for bulk pricing or special requests.',

    // Client Chat & Admin Chat
    chatSupport: 'Chat Support',
    typeMessage: 'Type a message...',
    send: 'Send',
    supportDesk: 'Support Desk',
    selectClient: 'Select a client to start chatting',

    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    totalRevenue: 'Total Revenue',
    activeWorkers: 'Active Workers',
    supplierCount: 'Supplier Count',
    analyticsChart: 'Analytics Chart',
    recentSales: 'Recent Sales',
    quickActions: 'Quick Actions',
    systemOverview: 'Real-time overview of manufacturing and supply chain operations.',

    // Admin Inventory
    coirProductsDb: 'Coir Products Database',
    addProduct: 'Add New Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    prodName: 'Product Name',
    description: 'Description',
    imageUrl: 'Image URL',
    stockTons: 'Stock (Tons)',
    pricePerTonRs: 'Price per Ton (₹)',
    saveProduct: 'Save Product',

    // Admin Orders
    manageClientOrders: 'Manage client orders and update shipment tracking status.',
    updateStatus: 'Update Status',
    currentStatus: 'Current Status',

    // Admin Workers
    workersDirectory: 'Workers Directory',
    manageProductionWorkers: 'Manage production staff and shift schedules.',
    addWorker: 'Add Worker',
    role: 'Role',
    shift: 'Shift',

    // Admin Suppliers
    suppliersDirectory: 'Suppliers Directory',
    manageRawSuppliers: 'Manage coconut husk and fiber raw material suppliers.',
    addSupplier: 'Add Supplier',
    rawMaterial: 'Raw Material',
    contactNumber: 'Contact Number',

    // Admin Scanner
    qrScanner: 'QR Code Scanner',
    scanBundleQR: 'Scan coir bundle or order tracking QR code.',
    bundlesScanned: 'Bundles Scanned',
    activeScanner: 'Active Scanner',

    // AI Chatbot Widget
    aiAssistant: 'Smart Coir AI Assistant',
    askAI: 'Ask about products, orders, or coir industry specs...',
    suggestedQuestions: 'Suggested Questions',
    aiIntro: 'Hello! I am your Smart Coir AI Assistant. Ask me anything about our coir products, processing stages, pricing, or order logistics.',
    online: 'Online',
    aiSug1: 'Coir Price & Grades',
    aiSug1Q: 'What are the coir quality grades and pricing?',
    aiSug2: 'Manufacturing Process',
    aiSug2Q: 'How is industrial coir fiber extracted and processed?',
    aiSug3: 'Order & Delivery Info',
    aiSug3Q: 'How do I place and track my orders?',
    aiSug4: 'Tech Specs',
    aiSug4Q: 'What are the technical specs of premium export grade rope?',

    // Additional keys
    loadingDashboard: 'Loading your dashboard...',
    loadingRecentOrders: 'Loading recent orders...',
    noOrdersFoundClickHere: 'No orders found. Click here to browse products and place your first order.',
    orderRef: 'Order Ref',
    items: 'Items',
    totalAmount: 'Total Amount',
    productsUnit: 'product(s)',
    orderCoirProducts: '🟢 Order Coir Products',
    updateCompanyProfile: '👤 Update Company Profile',
    supportInquiry: '✉️ Support & Inquiry',
    needAssistance: 'Need Assistance?',
    assistanceDesc: 'Connect with our supply chain team directly for wholesale pricing, custom dimension ropes, or shipping logistics details.',
    inquireNow: 'Inquire Now',
    allCategories: 'All Categories',
    coirRopes: 'Coir Ropes',
    browseProductInventory: 'Browse Product Inventory',
    browseInventoryDesc: 'Select items from our sustainable industrial coconut fiber products catalog to place orders.',
    loadingCatalog: 'Loading products catalog...',
    noProductsMatch: 'No products match your filters. Try clearing your search or selecting another category.',
    ton: 'ton',
    loadingSpecs: 'Loading specifications...',
    couldNotLoadDetails: 'Could not load product details.',
    grade: 'Grade',
    technicalSpecifications: 'Technical Specifications',
    fiberComposition: 'Fiber Composition',
    yarnRopeColor: 'Yarn/Rope Color',
    moistureLevel: 'Moisture Level',
    tensileStrength: 'Tensile Strength',
    lengthPerUnit: 'Length per Unit',
    thicknessDiameter: 'Thickness / Diameter',
    qrCodeInventoryTag: 'QR Code Inventory Tag',
    qrVerifyDesc: 'Scan this QR code to instantly verify product specifications, warehouse SKU codes, and live pricing.',
    orderRequestPlaced: 'Order Request Placed!',
    orderSuccessDesc: 'Your order has been recorded successfully. Redirecting you to your order tracking portal now...',
    placeOrderRequest: 'Place Order Request',
    provideAddress: 'Please provide a shipping delivery address.',
    rate: 'Rate',
    shippingDeliveryAddress: 'Shipping Delivery Address',
    addressPlaceholder: 'Enter full shipping address with postal code...',
    preferredPaymentMethod: 'Preferred Payment Method',
    bankTransferOption: 'Bank Wire Transfer (wholesale)',
    lcOption: 'L/C (Letter of Credit - Export)',
    net30Option: 'Net 30 Account (Approved Corporates)',
    orderNotesOptional: 'Order Notes (Optional)',
    notesPlaceholder: 'E.g. Custom packaging requirements, delivery timings',
    subtotal: 'Subtotal',
    estimatedGst: 'Estimated GST (18%)',
    shippingLogistics: 'Shipping / Logistics',
    free: 'FREE',
    estimatedTotal: 'Estimated Total',
    submittingOrderRequest: 'Submitting Order Request...',
    statusPending: 'Pending',
    statusConfirmed: 'Confirmed',
    statusProcessing: 'Processing',
    statusShipped: 'Shipped',
    statusDelivered: 'Delivered',
    profileSettingsDesc: 'Update your personal, corporate, and default delivery address details.',
    profileUpdatedSuccess: 'Profile updated successfully!',
    profileUpdatedError: 'Failed to update profile. Please try again.',
    companyContactInfo: 'Company & Contact Information',
    contactPhone: 'Contact Phone',
    defaultCorporateAddress: 'Default Corporate Delivery Address',
    streetAddress: 'Street Address',
    streetPlaceholder: 'E.g. 100 Main St, Suite 400',
    city: 'City',
    stateProvince: 'State / Province',
    country: 'Country',
    zipPostalCode: 'Zip / Postal Code',
    saveProfile: 'Save Profile',
    contactAdminDesc: 'Get in touch with our factory admin, logistics coordinators, or wholesale support team.',
    fillSubjectMessage: 'Please fill in both subject and message.',
    inquirySubmittedSuccess: 'Your support inquiry has been submitted! Our supply chain team will contact you shortly.',
    inquirySubmittedError: 'Failed to submit inquiry. Please try again.',
    factoryHeadquarters: 'Factory Headquarters',
    address: 'Address',
    wholesaleHelpline: 'Wholesale Helpline',
    emailSupport: 'E-mail Support',
    directBulkInquiries: 'Direct Bulk Inquiries',
    bulkInquiryDesc: 'For shipments exceeding 10 tons per month, custom color yarn blends, or specific fiber tensile strength certifications, please submit a formal inquiry form specifying your specifications.',
    submitSupportInquiry: 'Submit Support Inquiry',
    subject: 'Subject',
    subjectPlaceholder: 'E.g. Inquiry regarding custom rope thickness',
    message: 'Message',
    messagePlaceholder: 'Detail your questions or order requests here...',
    sendInquiryBtn: 'Send Inquiry',
    submittingInquiry: 'Submitting inquiry...',
    liveSupportDesk: 'Live Support Desk',
    liveSupportDesc: 'Chat in real-time with our operations control room for supply chain queries or orders.',
    supportOperators: 'Support Operators',
    loadingSupportDesk: 'Loading support desk...',
    noOperatorsOnline: 'No operators online. Please leave a support inquiry via Contact Admin.',
    operationsAgent: 'Operations Agent',
    loadingMessages: 'Loading message history...',
    welcomeChatWith: '👋 Welcome! Send a message to start chatting with',
    isTypingText: 'is typing...',
    selectAgentChat: 'Select a support agent from the left to start chatting',
    opsDashboardTitle: 'Operations Control Dashboard',
    opsDashboardDesc: 'Real-time coir manufacturing metrics, inventory reserves, and active client logistics orders.',
    addProductBtn: '➕ Add Product',
    viewCatalogBtn: '🛠️ View Catalog',
    factorySalesRevenue: 'Factory Sales Revenue',
    receivedOrders: 'Received Orders',
    registeredClients: 'Registered Clients',
    lowStockItems: 'Low Stock Items',
    incomingClientOrders: 'Incoming Client Orders',
    processOrdersBtn: 'Process Orders →',
    loadingOpsLogs: 'Loading operational logs...',
    noOrdersReceived: 'No orders received yet. Active client portals will populate orders here.',
    orderTableHead: 'Order',
    clientCompanyTableHead: 'Client / Company',
    grandTotalTableHead: 'Grand Total',
    logDateTableHead: 'Log Date',
    prodCatalogStockLevels: 'Product catalog & Stock levels',
    stockQuantityTableHead: 'Stock Quantity',
    outOfStock: 'Out of Stock',
    lowStockStatus: 'Low Stock',
    inStockStatus: 'In Stock',
    deleteBtn: '🗑️ Delete',
    logisticsControl: 'Logistics Control',
    trackActiveShipments: '🚛 Track Active Shipments',
    manageWorkerLogs: '👷 Manage Worker Logs',
    aiBusinessInsights: '🔮 AI Business Insights',
    analyzingTrends: 'Analyzing sales & stock trends...',
    noInsightsYet: 'No insights generated yet.',
    systemAlert: 'System Alert',
    systemAlertDesc: 'Ensure daily production metrics and raw coconut husk supplies are updated regularly for demand forecasting accuracy.',
    adjustStockLevel: 'Adjust Stock Level',
    productLabel: 'Product:',
    qtyInStockKg: 'Quantity in Stock (kg)',
    cancelBtn: 'Cancel',
    saveChangesBtn: 'Save Changes',
    createNewProductStockEntry: 'Create New Product & Stock Entry',
    registerProductDesc: 'Register a new product in the coir catalog and initialize its warehouse stock levels.',
    skuLabel: 'SKU (Stock Keeping Unit)',
    qualityGradeLabel: 'Quality Grade',
    priceInrPerKg: 'Price (INR per kg)',
    unitPackagingWeightKg: 'Unit Packaging Weight (kg)',
    initialStockQtyKg: 'Initial Stock Quantity (kg)',
    minStockAlertLimitKg: 'Min Stock Alert Limit (kg)',
    prodInventoryReserves: 'Product Inventory Reserves',
    manageCatalogStockDesc: 'Manage the factory products catalog and view warehouse stock levels.',
    totalCatalogProducts: 'Total Catalog Products',
    totalInStock: 'Total In Stock',
    lowStockWarnings: 'Low Stock Warnings',
    outOfStockItems: 'Out of Stock Items',
    warehouseStockLevels: 'Warehouse Stock Levels',
    loadingStockDetails: 'Loading stock details...',
    noInventoryFound: "No inventory found. Click 'Add New Product' to populate the system.",
    warehouseTableHead: 'Warehouse',
    createSeedProductBtn: 'Create & Seed Product',
    registeringProduct: 'Registering Product...',
    logisticsClientPurchases: 'Logistics & Client Purchases',
    opsOrdersDesc: 'Process wholesale coir order requests, update tracking numbers, and manage payments.',
    incomingOrdersTitle: 'Incoming Orders',
    noOrdersInSystem: 'No orders received in the system.',
    directClient: 'Direct Client',
    paidStatus: 'Paid',
    unpaidStatus: 'Unpaid',
    processOrderTitle: 'Process Order',
    clientLabel: 'Client:',
    workflowStatusActions: 'Workflow Status Actions',
    confirmOrderBtn: 'Confirm Order',
    beginProcessingBtn: '⚙️ Begin Processing',
    shipBtn: 'Ship (Enter Logistics)',
    markDeliveredBtn: 'Mark Delivered',
    billingPaymentStatus: 'Billing & Payment Status',
    paymentStatusLabel: 'Payment Status:',
    approvePaymentBtn: 'Approve Payment',
    resetUnpaidBtn: 'Reset Unpaid',
    deliveryAddress: 'Delivery Address',
    purchasedItems: 'Purchased Items',
    quantityLabel: 'Quantity:',
    selectOrderProcessDesc: 'Select an order from the list to process shipment logistics and manage billings.',
    enterShippingDetailsTitle: 'Enter Shipping Logistics Details',
    logisticsCarrierLabel: 'Logistics Carrier',
    trackingNumberLabel: 'Tracking Number',
    estimatedDeliveryDateLabel: 'Estimated Delivery Date',
    dispatchOrderBtn: 'Dispatch Order',
    workersDirectoryDesc: 'Monitor worker logs, department tasks, and active factory shifts.',
    shiftOpsLabel: 'Shift Operations (Phase 4 WIP)',
    activeStatus: 'Active',
    onLeaveStatus: 'On Leave',
    machineOperator: 'Machine Operator',
    qualityAuditor: 'Quality Auditor',
    logisticsHandler: 'Logistics Handler',
    decorticationUnit: 'Decortication Unit',
    inspectionDept: 'Inspection Department',
    warehouseA: 'Warehouse A',
    suppliersDirectoryDesc: 'Monitor coir material raw supply vendors and quality performance scores.',
    supplyChainVendorsLabel: 'Supply Chain Vendors (Phase 4 WIP)',
    contactColon: 'Contact:',
    suppliesColon: 'Supplies:',
    rawCoconutHusks: 'Raw Coconut Husks',
    decorticatedGreenHusks: 'Decorticated Green Husks',
    scannerDesc: 'Scan or upload product QR codes to instantly view details and adjust inventory stock.',
    scanInputTitle: 'Scan Input',
    scanPromptDesc: 'Upload a QR code image, use camera, or run a simulated scan',
    scanningProductTag: 'Scanning product tag...',
    uploadQrImageBtn: '📁 Upload QR Image',
    stopCameraBtn: '⏹ Stop Camera',
    liveCameraBtn: '📷 Live Camera',
    demoScanBtn: '🎯 Demo Scan',
    recentScansTitle: 'Recent Scans',
    scanResultTitle: 'Scan Result',
    demoDataBadge: 'Demo Data',
    weightLabel: 'Weight',
    currentStockLabel: 'Current Stock',
    stockAdjustmentTitle: '📦 Stock Adjustment',
    addStockBtn: '+ Add Stock',
    removeStockBtn: '− Remove Stock',
    adjustmentNoteLabel: 'Adjustment Note (Optional)',
    adjustmentNotePlaceholder: 'e.g., Inbound shipment, damaged goods...',
    addStockSubmit: '+ Add',
    removeStockSubmit: '− Remove',
    units: 'Units',
    noProductScanned: 'No Product Scanned',
    noProductScannedDesc: 'Upload a QR code image, use your device camera, or click "Demo Scan" to simulate a warehouse scan.',
    opsSupportDesk: 'Operations Support Desk',
    opsChatDesc: 'Resolve supply chain requests and chat in real-time with registered factory buyers.',
    activeChatsTab: 'Active Chats',
    clientContactsTab: 'Client Contacts',
    loadingChatThreads: 'Loading chat threads...',
    noActiveChatsDesc: 'No active support threads. Clients will populate here once they start a live chat session.',
    unknownClient: 'Unknown Client',
    noMessagesYet: 'No messages yet',
    loadingClientsList: 'Loading clients list...',
    noBuyersRegistered: 'No buyers registered in the database.',
    buyerRepFrom: 'Buyer Representative from',
    loadingMessageLogs: 'Loading message logs...',
    noMessagesThread: 'No messages in this chat thread. Type below to start the support session.',
    typeSupportReplyPlaceholder: 'Type support reply...',
    replyBtn: 'Reply',
    selectBuyerThreadDesc: 'Select an active buyer thread or lookup a client to start support chat',
  },
  ta: {
    // Navbar
    login: 'உள்நுழைக',
    getStarted: 'தொடங்குங்கள்',

    // Hero
    badge: 'தொழில்துறை 4.0 தளம்',
    heroTitle1: 'தென்னை நாரை',
    heroTitle2: 'மாற்றுகிறோம்',
    heroTitle3: 'நிலையான',
    heroTitle4: 'தொழிற்சாலை பொருட்களாக',
    heroDesc: 'ஸ்மார்ட் கயிறு உற்பத்தி & விநியோகச் சங்கிலி தளம் — முழுமையான உற்பத்தி கண்காணிப்பு, சரக்கு மேலாண்மை மற்றும் நிகழ்நேர விநியோகச் சங்கிலி அறிவுத்திறன்.',
    viewInventory: 'சரக்குகளைக் காண்க',
    tonsMonth: 'டன் / மாதம்',
    countries: 'நாடுகள்',
    qualityRate: 'தர விகிதம்',
    scrollExplore: 'ஆராய உருட்டவும்',

    // Stats
    statsTitle: 'பேசும் எண்கள்',
    statsSubtitle: 'எங்கள் உற்பத்தி அளவீடுகள் சிறப்பின் கதையைச் சொல்கின்றன',
    dailyOutput: 'தினசரி உற்பத்தி',
    clientsServed: 'வாடிக்கையாளர்கள்',
    exportCountries: 'ஏற்றுமதி நாடுகள்',
    yearsExperience: 'ஆண்டு அனுபவம்',
    ourImpact: 'எங்கள் தாக்கம்',
    performance: 'செயல்திறன்',
    industryLeading: 'தொழில்துறையில் முன்னணியில்',
    statsDesc: 'ஒப்பற்ற தரம், நிலைத்தன்மை மற்றும் நம்பகத்தன்மையுடன் உலகளவில் பிரீமியம் கயிறு தயாரிப்புகளை வழங்குதல்',
    tonsProducedMonthly: 'மாதாந்திர உற்பத்தி அளவு (டன்)',
    highCapacityMfg: 'உயர் திறன் தொழில்துறை உற்பத்தி',
    globalCoverage: 'உலகளாவிய விநியோகச் சங்கிலி கவரேஜ்',
    activeClients: 'செயலில் உள்ள வாடிக்கையாளர்கள்',
    trustedPartnerships: 'நம்பகமான வணிக கூட்டாண்மை',
    qualityAssurance: 'தர உத்தரவாதம்',
    isoCertified: 'ஐஎஸ்ஓ சான்றளிக்கப்பட்ட ஆய்வு செயல்முறை',

    // Manufacturing
    mfgTitle: 'உற்பத்தி செயல்முறை',
    mfgSubtitle: 'பச்சை தென்னை ஓட்டிலிருந்து உயர்தர முடிக்கப்பட்ட பொருட்கள் வரை',

    // CTA
    ctaTitle: 'உங்கள் விநியோகச் சங்கிலியை மாற்ற தயாரா?',
    ctaDesc: 'உயர்தர கயிறு பொருட்கள் மற்றும் திறமையான விநியோகச் சங்கிலி மேலாண்மைக்காக ஸ்மார்ட் கயிறை நம்பும் நூற்றுக்கணக்கான வணிகங்களுடன் இணையுங்கள்.',
    ctaButton: 'உங்கள் பயணத்தைத் தொடங்குங்கள்',
    whyChooseUs: 'ஏன் எங்களை தேர்வு செய்ய வேண்டும்',
    futureCoirTitle: 'எதிர்காலம்',
    coirMfg: 'கயிறு உற்பத்தி',
    ctaLeftDesc: 'பிரீமியம் கயிறு தயாரிப்புகளை வழங்க பாரம்பரிய கைவினைத்திறனுடன் அதிநவீன தொழில்நுட்பத்தை இணைக்கிறோம். எங்கள் ஸ்மார்ட் தளம் உற்பத்தி மற்றும் விநியோகச் சங்கிலி செயல்முறை முழுவதையும் கண்காணிக்க உதவுகிறது.',
    startFreeTrial: 'இலவச சோதனையைத் தொடங்கு',
    scheduleDemo: 'டெமோ பதிவு செய்',
    feat1Title: 'நிகழ்நேர கண்காணிப்பு',
    feat1Desc: 'நேரடி டாஷ்போர்டுகள் மற்றும் உடனடி விழிப்பூட்டல்களுடன் உற்பத்தி, சரக்கு மற்றும் விநியோகங்களைக் கண்காணிக்கவும்.',
    feat2Title: 'AI-ஆற்றல் பகுப்பாய்வு',
    feat2Desc: 'ஸ்மார்ட் பகுப்பாய்வு தேவையை கணிக்கிறது, இருப்பு அளவை மேம்படுத்துகிறது மற்றும் வருவாய் வளர்ச்சியை அதிகரிக்கிறது.',
    feat3Title: 'விநியோகச் சங்கிலி கட்டுப்பாடு',
    feat3Desc: 'தென்னை உமி சேகரிப்பு முதல் உலகளாவிய தயாரிப்பு விநியோகம் வரை முழுமையான பார்வை.',
    feat4Title: 'தர உத்தரவாதம்',
    feat4Desc: 'ஒவ்வொரு கட்டத்திலும் ஐஎஸ்ஓ சான்றளிக்கப்பட்ட சோதனை ஏற்றுமதிக்கு தயாரான உயர்தர தயாரிப்புகளை உறுதி செய்கிறது.',

    // Footer
    footerDesc: 'உயர்தர கயிறு உற்பத்தி மற்றும் விநியோகச் சங்கிலி மேலாண்மை தளம். தென்னை நாரை நிலையான தொழிற்சாலை பொருட்களாக மாற்றுகிறது.',
    quickLinks: 'விரைவு இணைப்புகள்',
    home: 'முகப்பு',
    about: 'எங்களைப் பற்றி',
    contact: 'தொடர்பு',
    contactInfo: 'தொடர்பு தகவல்',
    rights: 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    products: 'தயாரிப்புகள்',
    company: 'நிறுவனம்',
    platform: 'போர்டல்',
    support: 'ஆதரவு',
    coirRope: 'கயிறு',
    coirYarn: 'கயிறு நூல்',
    fiberBundles: 'நார் மூட்டைகள்',
    rawFiber: 'மூல நார்',
    aboutUs: 'எங்களைப் பற்றி',
    manufacturing: 'தயாரிப்பு',
    qualityStandards: 'தரநிலைகள்',
    careers: 'வேலைவாய்ப்பு',
    inventorySystem: 'சரக்கு முறை',
    orderTracking: 'ஆர்டர் கண்காணிப்பு',
    contactUs: 'தொடர்பு கொள்ள',
    documentation: 'ஆவணங்கள்',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    liveChat: 'நேரடி அரட்டை',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',

    langEn: 'English',
    langTa: 'தமிழ்',
    langHi: 'हिन्दी',

    // Auth
    signInPortal: 'உள்நுழைவு தளம்',
    selectRole: 'தொடர உங்கள் போர்டல் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    clientPortal: 'வாடிக்கையாளர் போர்டல்',
    adminPanel: 'நிர்வாக குழு',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    emailPlaceholder: 'name@company.com',
    password: 'கடவுச்சொல்',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    signInBtn: 'உள்நுழைக',
    authenticating: 'சரிபார்க்கிறது...',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    createOneNow: 'புதிய கணக்கை உருவாக்கு',
    createAccountPortal: 'கிளையண்ட் கணக்கு உருவாக்கம்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    backToLogin: 'இங்கே உள்நுழைக',
    registerBtn: 'நிறுவனத்தை பதிவுசெய்',
    registering: 'பதிவு செய்கிறது...',
    fullName: 'முழு பெயர்',
    companyName: 'நிறுவனத்தின் பெயர்',
    companyAddress: 'நிறுவன முகவரி',
    phone: 'தொலைபேசி எண்',
    step: 'படி',
    personalDetails: 'தனிப்பட்ட விவரங்கள்',
    companyDetails: 'நிறுவன விவரங்கள்',
    continue: 'தொடரவும்',
    buyCoir: 'கயிறு தயாரிப்புகளை வாங்க',
    back: 'பின்செல்',

    // Sidebar & Menus
    dashboard: 'டாஷ்போர்டு',
    inventory: 'சரக்கு',
    orders: 'எனது ஆர்டர்கள்',
    chat: 'ஆதரவு அரட்டை',
    profile: 'சுயவிவர அமைப்புகள்',
    contactAdmin: 'நிர்வாகியைத் தொடர்பு கொள்ள',
    scanner: 'க்யூஆர் ஸ்கேனர்',
    workers: 'தொழிலாளர்கள் விபரம்',
    suppliers: 'சப்ளையர்கள் விபரம்',
    adminHome: 'நிர்வாக முகப்பு',
    manageProducts: 'தயாரிப்பு மேலாண்மை',
    clientOrders: 'வாடிக்கையாளர் ஆர்டர்கள்',
    liveSupport: 'நேரடி ஆதரவு',
    systemStatus: 'நேரடி சர்வர்',
    notifications: 'அறிவிப்புகள்',
    markAllRead: 'அனைத்தையும் படித்ததாகக் குறி',
    noNotifications: 'அறிவிப்புகள் இல்லை',
    signOut: 'வெளியேறு',

    // Client Dashboard
    welcome: 'வரவேற்கிறோம்',
    repOf: 'பிரதிநிதி',
    manageCoirOrders: 'உங்கள் ஆர்டர்களை நிர்வகித்து விநியோகத்தை கண்காணிக்கவும்.',
    browseCatalog: 'சரக்கு பட்டியல்',
    orderHistory: 'ஆர்டர் வரலாறு',
    totalOrdersPlaced: 'மொத்த ஆர்டர்கள்',
    activeShipments: 'செயலில் உள்ள ஆர்டர்கள்',
    completedDeliveries: 'நிறைவடைந்த விநியோகம்',
    totalInvestments: 'மொத்த முதலீடு',
    recentOrders: 'சமீபத்திய ஆர்டர்கள்',
    noOrders: 'ஆர்டர்கள் எதுவும் இல்லை',
    viewAllOrders: 'அனைத்து ஆர்டர்களையும் காண்க',
    orderId: 'ஆர்டர் ஐடி',
    date: 'தேதி',
    total: 'மொத்தம்',
    status: 'நிலை',
    actions: 'செயல்கள்',
    track: 'கண்காணி',

    // Client Inventory
    availableProducts: 'கிடைக்கும் கயிறு தயாரிப்புகள்',
    searchPlaceholder: 'கயிறு தயாரிப்புகளைத் தேடுங்கள்...',
    stock: 'இருப்பு',
    price: 'விலை',
    viewDetails: 'விவரங்களைக் காண்க',
    categories: 'வகைகள்',

    // Client Products Detail
    productDetails: 'தயாரிப்பு விவரங்கள்',
    specifications: 'விவரக்குறிப்புகள்',
    pricePerTon: 'ஒரு டன்னின் விலை',
    availableQty: 'கிடைக்கும் அளவு',
    backToInventory: 'சரக்கு பட்டியலுக்கு திரும்பு',
    placeOrder: 'ஆர்டர் செய்',
    orderEstimator: 'மதிப்பீட்டாளர் மற்றும் விவரக்குறிப்பு',
    fiberGrade: 'நார் தரம்',
    moistureLimit: 'ஈரப்பத அளவு',
    baleWeight: 'பேல் எடை',
    quantityTons: 'அளவு (டன்)',
    estimatedPrice: 'மதிப்பிடப்பட்ட விலை',
    taxFees: 'வரி மற்றும் கப்பல் கட்டணம்',
    grandTotal: 'மொத்தத் தொகை',
    submittingOrder: 'ஆர்டர் சமர்ப்பிக்கப்படுகிறது...',
    confirmOrder: 'ஆர்டரை உறுதிசெய்',
    estimatedDelivery: 'மதிப்பிடப்பட்ட விநியோகம்',

    // Client Profile
    companyProfileSettings: 'நிறுவன சுயவிவர அமைப்புகள்',
    updateCompanyDetails: 'உங்கள் நிறுவனத்தின் தகவல்களைப் புதுப்பிக்கவும்.',
    companyDetails: 'நிறுவன விவரங்கள்',
    saveChanges: 'மாற்றங்களைச் சேமி',
    saving: 'சேமிக்கப்படுகிறது...',

    // Client Contact
    contactOffice: 'அலுவலகத் தொடர்பு',
    sendInquiry: 'ஆதரவு விசாரணையை அனுப்பு',
    subject: 'விஷயம்',
    message: 'செய்தி',
    sendBtn: 'செய்தி அனுப்பு',
    sending: 'அனுப்பப்படுகிறது...',
    contactDesc: 'மொத்த விலை அல்லது சிறப்பு கோரிக்கைகளுக்கு எங்களைத் தொடர்பு கொள்ளவும்.',

    // Client Chat & Admin Chat
    chatSupport: 'நேரடி அரட்டை',
    typeMessage: 'செய்தியைத் தட்டச்சு செய்க...',
    send: 'அனுப்பு',
    supportDesk: 'ஆதரவு மேசை',
    selectClient: 'அரட்டையைத் தொடங்க ஒரு கிளையண்டைத் தேர்ந்தெடுக்கவும்',

    // Admin Dashboard
    adminDashboard: 'நிர்வாக டாஷ்போர்டு',
    totalRevenue: 'மொத்த வருவாய்',
    activeWorkers: 'செயலில் உள்ள தொழிலாளர்கள்',
    supplierCount: 'சப்ளையர்களின் எண்ணிக்கை',
    analyticsChart: 'பகுப்பாய்வு விளக்கப்படம்',
    recentSales: 'சமீபத்திய விற்பனை',
    quickActions: 'விரைவான செயல்கள்',
    systemOverview: 'உற்பத்தி மற்றும் விநியோகச் சங்கிலி நடவடிக்கைகளின் நிகழ்நேர கண்ணோட்டம்.',

    // Admin Inventory
    coirProductsDb: 'கயிறு தயாரிப்புகள் தரவுத்தளம்',
    addProduct: 'புதிய தயாரிப்பு சேர்',
    editProduct: 'தயாரிப்பைத் திருத்து',
    deleteProduct: 'தயாரிப்பை நீக்கு',
    prodName: 'தயாரிப்பு பெயர்',
    description: 'விளக்கம்',
    imageUrl: 'படத்தின் முகவரி',
    stockTons: 'இருப்பு (டன்)',
    pricePerTonRs: 'ஒரு டன்னின் விலை (₹)',
    saveProduct: 'தயாரிப்பைச் சேமி',

    // Admin Orders
    manageClientOrders: 'கிளையண்ட் ஆர்டர்களை நிர்வகித்து விநியோக நிலையைப் புதுப்பிக்கவும்.',
    updateStatus: 'நிலையைப் புதுப்பி',
    currentStatus: 'தற்போதைய நிலை',

    // Admin Workers
    workersDirectory: 'தொழிலாளர்கள் அடைவு',
    manageProductionWorkers: 'உற்பத்தி ஊழியர்கள் மற்றும் பணி நேரங்களை நிர்வகிக்கவும்.',
    addWorker: 'தொழிலாளரைச் சேர்',
    role: 'பங்கு',
    shift: 'பணி நேரம்',

    // Admin Suppliers
    suppliersDirectory: 'சப்ளையர்கள் அடைவு',
    manageRawSuppliers: 'தென்னை உமி மற்றும் நார் சப்ளையர்களை நிர்வகிக்கவும்.',
    addSupplier: 'சப்ளையரைச் சேர்',
    rawMaterial: 'மூலப்பொருள்',
    contactNumber: 'தொடர்பு எண்',

    // Admin Scanner
    qrScanner: 'க்யூஆர் கோடு ஸ்கேனர்',
    scanBundleQR: 'கயிறு மூட்டை அல்லது ஆர்டரின் க்யூஆர் குறியீட்டை ஸ்கேன் செய்யவும்.',
    bundlesScanned: 'ஸ்கேன் செய்யப்பட்ட மூட்டைகள்',
    activeScanner: 'செயலில் உள்ள ஸ்கேனர்',

    // AI Chatbot Widget
    aiAssistant: 'ஸ்மார்ட் கயிறு AI உதவியாளர்',
    askAI: 'தயாரிப்புகள், ஆர்டர்கள் அல்லது கயிறு தொழில் பற்றி கேளுங்கள்...',
    suggestedQuestions: 'பரிந்துரைக்கப்பட்ட கேள்விகள்',
    aiIntro: 'வணக்கம்! நான் உங்கள் ஸ்மார்ட் கயிறு AI உதவியாளர். தயாரிப்புகள், தயாரிப்பு நிலைகள், விலைகள் அல்லது ஆர்டர்கள் பற்றி கேளுங்கள்.',
    online: 'ஆன்லைன்',
    aiSug1: 'விலை & தரம்',
    aiSug1Q: 'கயிறு தரம் மற்றும் விலைகள் என்ன?',
    aiSug2: 'உற்பத்தி செயல்முறை',
    aiSug2Q: 'தென்னை நார் எவ்வாறு பிரித்தெடுக்கப்பட்டு பதப்படுத்தப்படுகிறது?',
    aiSug3: 'ஆர்டர் & விநியோகம்',
    aiSug3Q: 'ஆர்டரை எவ்வாறு உருவாக்குவது மற்றும் கண்காணிப்பது?',
    aiSug4: 'தொழில்நுட்ப விவரம்',
    aiSug4Q: 'ஏற்றுமதி தர கயிற்றின் தொழில்நுட்ப விவரக்குறிப்புகள் என்ன?',

    // Additional keys
    loadingDashboard: 'உங்கள் டாஷ்போர்டு ஏற்றப்படுகிறது...',
    loadingRecentOrders: 'சமீபத்திய ஆர்டர்கள் ஏற்றப்படுகிறது...',
    noOrdersFoundClickHere: 'ஆர்டர்கள் எதுவும் இல்லை. தயாரிப்புகளைப் பார்க்கவும் முதல் ஆர்டரைச் செய்யவும் இங்கே கிளிக் செய்யவும்.',
    orderRef: 'ஆர்டர் குறிப்பு',
    items: 'பொருட்கள்',
    totalAmount: 'மொத்த தொகை',
    productsUnit: 'தயாரிப்பு(கள்)',
    orderCoirProducts: '🟢 கயிறு தயாரிப்புகளை ஆர்டர் செய்ய',
    updateCompanyProfile: '👤 நிறுவன சுயவிவரத்தைப் புதுப்பிக்குக',
    supportInquiry: '✉️ ஆதரவு & விசாரணை',
    needAssistance: 'உதவி தேவையா?',
    assistanceDesc: 'மொத்த விலை அல்லது சிறப்பு பரிமாணக் கயிறுகள் மற்றும் கப்பல் விவரங்களுக்கு எங்கள் குழுவைத் தொடர்பு கொள்ளவும்.',
    inquireNow: 'இப்போது விசாரிக்கவும்',
    allCategories: 'அனைத்து பிரிவுகள்',
    coirRopes: 'கயிறுகள்',
    browseProductInventory: 'தயாரிப்பு சரக்கு பட்டியல்',
    browseInventoryDesc: 'ஆர்டர்களைச் செய்ய எங்கள் நிலையான தென்னை நார் தயாரிப்புகள் பட்டியலிலிருந்து பொருட்களைத் தேர்ந்தெடுக்கவும்.',
    loadingCatalog: 'தயாரிப்புகள் பட்டியல் ஏற்றப்படுகிறது...',
    noProductsMatch: 'உங்கள் வடிப்பான்களுடன் எந்த தயாரிப்புகளும் பொருந்தவில்லை. தேடலை அழிக்கவும் அல்லது வேறு பிரிவைத் தேர்ந்தெடுக்கவும்.',
    ton: 'டன்',
    loadingSpecs: 'விவரக்குறிப்புகள் ஏற்றப்படுகிறது...',
    couldNotLoadDetails: 'தயாரிப்பு விவரங்களை ஏற்ற முடியவில்லை.',
    grade: 'Grade தரம்',
    technicalSpecifications: 'தொழில்நுட்ப விவரக்குறிப்புகள்',
    fiberComposition: 'நார் கலவை',
    yarnRopeColor: 'நூல்/கயிறு நிறம்',
    moistureLevel: 'ஈரப்பதம் அளவு',
    tensileStrength: 'இழுவிசை வலிமை',
    lengthPerUnit: 'ஒரு யூனிட்டின் நீளம்',
    thicknessDiameter: 'தடிமன் / விட்டம்',
    qrCodeInventoryTag: 'க்யூஆர் கோடு சரக்கு குறிச்சொல்',
    qrVerifyDesc: 'தயாரிப்பு விவரக்குறிப்புகள், கிடங்கு SKU குறியீடுகள் மற்றும் நேரடி விலையை உடனடியாக சரிபார்க்க இந்த க்யூஆர் குறியீட்டை ஸ்கேன் செய்யவும்.',
    orderRequestPlaced: 'ஆர்டர் கோரிக்கை சமர்ப்பிக்கப்பட்டது!',
    orderSuccessDesc: 'உங்கள் ஆர்டர் வெற்றிகரமாக பதிவு செய்யப்பட்டுள்ளது. இப்போது உங்கள் ஆர்டர் கண்காணிப்பு பக்கத்திற்கு திருப்பி விடப்படுகிறீர்கள்...',
    placeOrderRequest: 'ஆர்டர் கோரிக்கையைச் செய்க',
    provideAddress: 'கப்பல் விநியோக முகவரியை வழங்கவும்.',
    rate: 'விகிதம்',
    shippingDeliveryAddress: 'கப்பல் விநியோக முகவரி',
    addressPlaceholder: 'அஞ்சல் குறியீட்டுடன் முழுமையான விநியோக முகவரியை உள்ளிடவும்...',
    preferredPaymentMethod: 'விருப்பமான கட்டண முறை',
    bankTransferOption: 'வங்கி கம்பி பரிமாற்றம் (மொத்த விற்பனை)',
    lcOption: 'எல்/சி (கடன் கடிதம் - ஏற்றுமதி)',
    net30Option: 'நெட் 30 கணக்கு (அங்கீகரிக்கப்பட்ட நிறுவனங்கள்)',
    orderNotesOptional: 'ஆர்டர் குறிப்புகள் (விருப்பத்தேர்வு)',
    notesPlaceholder: 'உதாரணமாக: தனிப்பயன் பேக்கேஜிங் தேவைகள், விநியோக நேரம்',
    subtotal: 'துணைத்தொகை',
    estimatedGst: 'மதிப்பிடப்பட்ட ஜிஎஸ்டி (18%)',
    shippingLogistics: 'கப்பல் போக்குவரத்து / தளவாடங்கள்',
    free: 'இலவசம்',
    estimatedTotal: 'மதிப்பிடப்பட்ட மொத்தம்',
    submittingOrderRequest: 'ஆர்டர் கோரிக்கை சமர்ப்பிக்கப்படுகிறது...',
    statusPending: 'நிலுவையில்',
    statusConfirmed: 'உறுதி செய்யப்பட்டது',
    statusProcessing: 'செயலாக்கத்தில்',
    statusShipped: 'அனுப்பப்பட்டது',
    statusDelivered: 'விநியோகிக்கப்பட்டது',
    profileSettingsDesc: 'உங்கள் தனிப்பட்ட, கார்ப்பரேட் மற்றும் விநியோக முகவரி விவரங்களைப் புதுப்பிக்கவும்.',
    profileUpdatedSuccess: 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    profileUpdatedError: 'சுயவிவரத்தைப் புதுப்பிப்பதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    companyContactInfo: 'நிறுவனம் & தொடர்புத் தகவல்',
    contactPhone: 'தொடர்பு எண்',
    defaultCorporateAddress: 'இயல்புநிலை கார்ப்பரேட் விநியோக முகவரி',
    streetAddress: 'தெரு முகவரி',
    streetPlaceholder: 'உதாரணம்: 100 மெயின் தெரு, அறை 400',
    city: 'நகரம்',
    stateProvince: 'மாநிலம் / மாகாணம்',
    country: 'நாடு',
    zipPostalCode: 'அஞ்சல் குறியீடு',
    saveProfile: 'சுயவிவரத்தை சேமி',
    contactAdminDesc: 'எங்கள் தொழிற்சாலை நிர்வாகி, தளவாட ஒருங்கிணைப்பாளர்கள் அல்லது மொத்த விற்பனை குழுவைத் தொடர்பு கொள்ளவும்.',
    fillSubjectMessage: 'பொருள் மற்றும் செய்தி இரண்டையும் நிரப்பவும்.',
    inquirySubmittedSuccess: 'உங்கள் ஆதரவு விசாரணை சமர்ப்பிக்கப்பட்டது! எங்களது குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்.',
    inquirySubmittedError: 'விசாரணையைச் சமர்ப்பிப்பதில் தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    factoryHeadquarters: 'தொழிற்சாலை தலைமையகம்',
    address: 'முகவரி',
    wholesaleHelpline: 'மொத்த விற்பனை உதவி எண்',
    emailSupport: 'மின்னஞ்சல் ஆதரவு',
    directBulkInquiries: 'நேரடி மொத்த விசாரணைகள்',
    bulkInquiryDesc: 'மாதத்திற்கு 10 டன்களுக்கு மேல் ஏற்றுமதி, தனிப்பயன் வண்ண நூல் கலவைகள் அல்லது குறிப்பிட்ட இழுவிசை வலிமை சான்றிதழ்களுக்கு, விவரக்குறிப்புகளைக் குறிப்பிட்டு ஒரு முறையான விசாரணையைச் சமர்ப்பிக்கவும்.',
    submitSupportInquiry: 'ஆதரவு விசாரணையை சமர்ப்பிக்கவும்',
    subject: 'பொருள்',
    subjectPlaceholder: 'உதாரணம்: கயிற்றின் தடிமன் பற்றிய விசாரணை',
    message: 'செய்தி',
    messagePlaceholder: 'உங்கள் கேள்விகள் அல்லது ஆர்டர் கோரிக்கைகளை இங்கே விவரிக்கவும்...',
    sendInquiryBtn: 'விசாரணையை அனுப்புக',
    submittingInquiry: 'விசாரணை சமர்ப்பிக்கப்படுகிறது...',
    liveSupportDesk: 'நேரடி ஆதரவு மேசை',
    liveSupportDesc: 'விநியோகச் சங்கிலி வினவல்கள் அல்லது ஆர்டர்களுக்கு எங்கள் செயல்பாட்டு கட்டுப்பாட்டு அறையுடன் நிகழ்நேரத்தில் அரட்டையடிக்கவும்.',
    supportOperators: 'ஆதரவு பணியாளர்கள்',
    loadingSupportDesk: 'ஆதரவு மேசை ஏற்றப்படுகிறது...',
    noOperatorsOnline: 'தற்போது பணியாளர்கள் யாரும் ஆன்லைனில் இல்லை. நிர்வாகியைத் தொடர்பு கொள்ள பக்கம் வழியாக ஆதரவு விசாரணையை அனுப்பவும்.',
    operationsAgent: 'செயல்பாட்டு முகவர்',
    loadingMessages: 'செய்தி வரலாறு ஏற்றப்படுகிறது...',
    welcomeChatWith: '👋 வரவேற்கிறோம்! அரட்டையடிக்க செய்தி ஒன்றை அனுப்பவும்',
    isTypingText: 'தட்டச்சு செய்கிறார்...',
    selectAgentChat: 'அரட்டையடிக்க இடதுபுறத்தில் இருந்து ஒரு ஆதரவு முகவரைத் தேர்ந்தெடுக்கவும்',
    opsDashboardTitle: 'செயல்பாட்டு கட்டுப்பாட்டு டாஷ்போர்டு',
    opsDashboardDesc: 'நிகழ்நேர கயிறு உற்பத்தி அளவீடுகள், சரக்கு இருப்பு மற்றும் செயலில் உள்ள வாடிக்கையாளர் தளவாட ஆர்டர்கள்.',
    addProductBtn: '➕ தயாரிப்பு சேர்',
    viewCatalogBtn: '🛠️ பட்டியல் காண்க',
    factorySalesRevenue: 'தொழிற்சாலை விற்பனை வருவாய்',
    receivedOrders: 'பெறப்பட்ட ஆர்டர்கள்',
    registeredClients: 'பதிவு செய்யப்பட்ட வாடிக்கையாளர்கள்',
    lowStockItems: 'குறைந்த இருப்பு பொருட்கள்',
    incomingClientOrders: 'உள்வரும் வாடிக்கையாளர் ஆர்டர்கள்',
    processOrdersBtn: 'ஆர்டர்களை செயலாக்க →',
    loadingOpsLogs: 'செயல்பாட்டு பதிவுகள் ஏற்றப்படுகிறது...',
    noOrdersReceived: 'ஆர்டர்கள் எதுவும் இன்னும் பெறப்படவில்லை. வாடிக்கையாளர் போர்டல் ஆர்டர்கள் இங்கே காண்பிக்கப்படும்.',
    orderTableHead: 'ஆர்டர்',
    clientCompanyTableHead: 'வாடிக்கையாளர் / நிறுவனம்',
    grandTotalTableHead: 'மொத்த தொகை',
    logDateTableHead: 'பதிவு தேதி',
    prodCatalogStockLevels: 'தயாரிப்பு பட்டியல் & இருப்பு அளவுகள்',
    stockQuantityTableHead: 'இருப்பு அளவு',
    outOfStock: 'இருப்பு இல்லை',
    lowStockStatus: 'குறைந்த இருப்பு',
    inStockStatus: 'இருப்பில் உள்ளது',
    deleteBtn: '🗑️ நீக்கு',
    logisticsControl: 'தளவாடக் கட்டுப்பாடு',
    trackActiveShipments: '🚛 செயலில் உள்ள ஏற்றுமதிகளைக் கண்காணி',
    manageWorkerLogs: '👷 தொழிலாளர் பதிவுகளை நிர்வகி',
    aiBusinessInsights: '🔮 AI வணிக நுண்ணறிவு',
    analyzingTrends: 'விற்பனை மற்றும் பங்கு போக்குகளை பகுப்பாய்வு செய்கிறது...',
    noInsightsYet: 'நுண்ணறிவுகள் எதுவும் இன்னும் உருவாக்கப்படவில்லை.',
    systemAlert: 'கணினி எச்சரிக்கை',
    systemAlertDesc: 'தேவை கணிப்பு துல்லியத்திற்காக தினசரி உற்பத்தி அளவீடுகள் மற்றும் பச்சை தென்னை உமி விநியோகம் தொடர்ந்து புதுப்பிக்கப்படுவதை உறுதிசெய்யவும்.',
    adjustStockLevel: 'இருப்பு அளவை சரிசெய்',
    productLabel: 'தயாரிப்பு:',
    qtyInStockKg: 'இருப்பு அளவு (கிலோ)',
    cancelBtn: 'ரத்து செய்',
    saveChangesBtn: 'மாற்றங்களைச் சேமி',
    createNewProductStockEntry: 'புதிய தயாரிப்பு & இருப்பு பதிவை உருவாக்கு',
    registerProductDesc: 'கயிறு அட்டவணையில் ஒரு புதிய தயாரிப்பை பதிவுசெய்து அதன் கிடங்கு இருப்பு நிலைகளைத் தொடங்கவும்.',
    skuLabel: 'SKU (இருப்பு வைப்பு அலகு)',
    qualityGradeLabel: 'தர தரம்',
    priceInrPerKg: 'விலை (கிலோவிற்கு INR)',
    unitPackagingWeightKg: 'யூனிட் பேக்கேஜிங் எடை (கிலோ)',
    initialStockQtyKg: 'ஆரம்ப இருப்பு அளவு (கிலோ)',
    minStockAlertLimitKg: 'குறைந்தபட்ச இருப்பு எச்சரிக்கை வரம்பு (கிலோ)',
    prodInventoryReserves: 'தயாரிப்பு சரக்கு இருப்பு',
    manageCatalogStockDesc: 'தொழிற்சாலை தயாரிப்புகள் அட்டவணையை நிர்வகிக்கவும் மற்றும் கிடங்கு இருப்பு நிலைகளை பார்க்கவும்.',
    totalCatalogProducts: 'மொத்த தயாரிப்புகள்',
    totalInStock: 'மொத்த இருப்பு',
    lowStockWarnings: 'குறைந்த இருப்பு எச்சரிக்கைகள்',
    outOfStockItems: 'இருப்பு இல்லாத பொருட்கள்',
    warehouseStockLevels: 'கிடங்கு இருப்பு நிலைகள்',
    loadingStockDetails: 'இருப்பு விவரங்கள் ஏற்றப்படுகிறது...',
    noInventoryFound: 'சரக்கு எதுவும் இல்லை. கணினியில் புதிய தயாரிப்புகளை சேர்க்க "புதிய தயாரிப்பு சேர்" என்பதை கிளிக் செய்யவும்.',
    warehouseTableHead: 'கிடங்கு',
    createSeedProductBtn: 'தயாரிப்பை உருவாக்கி சேமிக்கவும்',
    registeringProduct: 'தயாரிப்பு பதிவு செய்யப்படுகிறது...',
    logisticsClientPurchases: 'தளவாடங்கள் & கிளையண்ட் கொள்முதல்',
    opsOrdersDesc: 'மொத்த கயிறு ஆர்டர் கோரிக்கைகளை செயலாக்கவும், கண்காணிப்பு எண்களைப் புதுப்பிக்கவும் மற்றும் கட்டணங்களை நிர்வகிக்கவும்.',
    incomingOrdersTitle: 'உள்வரும் ஆர்டர்கள்',
    noOrdersInSystem: 'கணினியில் ஆர்டர்கள் எதுவும் பெறப்படவில்லை.',
    directClient: 'நேரடி வாடிக்கையாளர்',
    paidStatus: 'கட்டணம் செலுத்தப்பட்டது',
    unpaidStatus: 'கட்டணம் செலுத்தப்படவில்லை',
    processOrderTitle: 'ஆர்டரை செயலாக்கு',
    clientLabel: 'வாடிக்கையாளர்:',
    workflowStatusActions: 'பணிப்பாய்வு நிலை செயல்கள்',
    confirmOrderBtn: 'ஆர்டரை உறுதிசெய்',
    beginProcessingBtn: '⚙️ செயலாக்கத்தைத் தொடங்கு',
    shipBtn: 'அனுப்பு (விவரங்களை உள்ளிடவும்)',
    markDeliveredBtn: 'விநியோகிக்கப்பட்டதாகக் குறிக்கவும்',
    billingPaymentStatus: 'பில்லிங் & கட்டண நிலை',
    paymentStatusLabel: 'கட்டண நிலை:',
    approvePaymentBtn: 'கட்டணத்தை அங்கீகரிக்கவும்',
    resetUnpaidBtn: 'கட்டணம் செலுத்தாததாக மாற்று',
    deliveryAddress: 'விநியோக முகவரி',
    purchasedItems: 'வாங்கப்பட்ட பொருட்கள்',
    quantityLabel: 'அளவு:',
    selectOrderProcessDesc: 'பில்லிங் மற்றும் கப்பல் விவரங்களை நிர்வகிக்க பட்டியலிலிருந்து ஒரு ஆர்டரைத் தேர்ந்தெடுக்கவும்.',
    enterShippingDetailsTitle: 'கப்பல் போக்குவரத்து விவரங்களை உள்ளிடவும்',
    logisticsCarrierLabel: 'தளவாட கேரியர்',
    trackingNumberLabel: 'கண்காணிப்பு எண்',
    estimatedDeliveryDateLabel: 'மதிப்பிடப்பட்ட விநியோக தேதி',
    dispatchOrderBtn: 'ஆர்டரை அனுப்பவும்',
    workersDirectoryDesc: 'தொழிலாளர் பதிவுகள், துறைப் பணிகள் மற்றும் செயலில் உள்ள தொழிற்சாலை மாற்றங்களைக் கண்காணிக்கவும்.',
    shiftOpsLabel: 'ஷிப்ட் செயல்பாடுகள் (கட்டம் 4 WIP)',
    activeStatus: 'செயலில்',
    onLeaveStatus: 'விடுப்பில்',
    machineOperator: 'இயந்திர ஆபரேட்டர்',
    qualityAuditor: 'தர தணிக்கையாளர்',
    logisticsHandler: 'தளவாடங்கள் கையாளுபவர்',
    decorticationUnit: 'உரித்தல் பிரிவு',
    inspectionDept: 'ஆய்வுத் துறை',
    warehouseA: 'கிடங்கு A',
    suppliersDirectoryDesc: 'கயிறு மூலப்பொருள் விற்பனையாளர்கள் மற்றும் தர செயல்திறன் மதிப்பெண்களைக் கண்காணிக்கவும்.',
    supplyChainVendorsLabel: 'விநியோகச் சங்கிலி விற்பனையாளர்கள் (கட்டம் 4 WIP)',
    contactColon: 'தொடர்புக்கு:',
    suppliesColon: 'வழங்குபவை:',
    rawCoconutHusks: 'பச்சை தென்னை உமி',
    decorticatedGreenHusks: 'உரிக்கப்பட்ட பச்சை உமி',
    scannerDesc: 'தயாரிப்பு விவரங்களை உடனடியாகப் பார்க்கவும் மற்றும் சரக்குகளைச் சரிசெய்யவும் க்யூஆர் குறியீடுகளை ஸ்கேன் செய்யவும் அல்லது பதிவேற்றவும்.',
    scanInputTitle: 'ஸ்கேன் உள்ளீடு',
    scanPromptDesc: 'க்யூஆர் குறியீடு படத்தைப் பதிவேற்றவும், கேமராவைப் பயன்படுத்தவும் அல்லது டெமோ ஸ்கேனை இயக்கவும்',
    scanningProductTag: 'தயாரிப்பு குறிச்சொல் ஸ்கேன் செய்யப்படுகிறது...',
    uploadQrImageBtn: '📁 க்யூஆர் படம் பதிவேற்று',
    stopCameraBtn: '⏹ கேமராவை நிறுத்து',
    liveCameraBtn: '📷 நேரடி கேமரா',
    demoScanBtn: '🎯 டெமோ ஸ்கேன்',
    recentScansTitle: 'சமீபத்திய ஸ்கேன்கள்',
    scanResultTitle: 'ஸ்கேன் முடிவு',
    demoDataBadge: 'டெமோ தரவு',
    weightLabel: 'எடை',
    currentStockLabel: 'தற்போதைய இருப்பு',
    stockAdjustmentTitle: '📦 இருப்பு சரிசெய்தல்',
    addStockBtn: '+ இருப்பு சேர்',
    removeStockBtn: '− இருப்பு குறை',
    adjustmentNoteLabel: 'சரிசெய்தல் குறிப்பு (விருப்பத்தேர்வு)',
    adjustmentNotePlaceholder: 'உதாரணமாக: உள்வரும் ஏற்றுமதி, சேதமடைந்த பொருட்கள்...',
    addStockSubmit: '+ சேர்',
    removeStockSubmit: '− குறை',
    units: 'அலகுகள்',
    noProductScanned: 'தயாரிப்பு எதுவும் ஸ்கேன் செய்யப்படவில்லை',
    noProductScannedDesc: 'ஒரு கிடங்கு ஸ்கேனை உருவகப்படுத்த க்யூஆர் குறியீடு படத்தைப் பதிவேற்றவும், கேமராவைப் பயன்படுத்தவும் அல்லது "டெமோ ஸ்கேன்" என்பதைக் கிளிக் செய்யவும்.',
    opsSupportDesk: 'செயல்பாட்டு ஆதரவு மேசை',
    opsChatDesc: 'விநியோகச் சங்கிலி கோரிக்கைகளைத் தீர்க்கவும் மற்றும் பதிவு செய்யப்பட்ட தொழிற்சாலை வாங்குபவர்களுடன் நிகழ்நேரத்தில் அரட்டையடிக்கவும்.',
    activeChatsTab: 'செயலில் உள்ள அரட்டைகள்',
    clientContactsTab: 'வாடிக்கையாளர் தொடர்புகள்',
    loadingChatThreads: 'அரட்டை இழைகள் ஏற்றப்படுகிறது...',
    noActiveChatsDesc: 'செயலில் உள்ள ஆதரவு அரட்டைகள் எதுவும் இல்லை. கிளையண்டுகள் நேரடி அரட்டை அமர்வைத் தொடங்கியவுடன் இங்கே காண்பிக்கப்படுவார்கள்.',
    unknownClient: 'அறியப்படாத வாடிக்கையாளர்',
    noMessagesYet: 'இன்னும் செய்திகள் இல்லை',
    loadingClientsList: 'வாடிக்கையாளர்கள் பட்டியல் ஏற்றப்படுகிறது...',
    noBuyersRegistered: 'தரவுத்தளத்தில் வாங்குபவர்கள் யாரும் பதிவு செய்யப்படவில்லை.',
    buyerRepFrom: 'வாங்குபவர் பிரதிநிதி',
    loadingMessageLogs: 'செய்தி பதிவுகள் ஏற்றப்படுகிறது...',
    noMessagesThread: 'இந்த அரட்டை நூலில் செய்திகள் இல்லை. ஆதரவு அமர்வைத் தொடங்க கீழே தட்டச்சு செய்யவும்.',
    typeSupportReplyPlaceholder: 'ஆதரவு பதிலை தட்டச்சு செய்க...',
    replyBtn: 'பதிலளி',
    selectBuyerThreadDesc: 'ஆதரவு அரட்டையைத் தொடங்க செயலில் உள்ள வாங்குபவர் இழையைத் தேர்ந்தெடுக்கவும் அல்லது கிளையண்ட்டைத் தேடவும்',
  },
  hi: {
    // Navbar
    login: 'लॉग इन',
    getStarted: 'शुरू करें',

    // Hero
    badge: 'उद्योग 4.0 प्लेटफॉर्म',
    heroTitle1: 'नारियल फाइबर को',
    heroTitle2: 'बदल रहे हैं',
    heroTitle3: 'टिकाऊ',
    heroTitle4: 'औद्योगिक उत्पादों में',
    heroDesc: 'स्मार्ट कॉयर मैन्युफैक्चरिंग & सप्लाई चेन प्लेटफॉर्म — उत्पादन निगरानी, इन्वेंटरी प्रबंधन और रियल-टाइम सप्लाई चेन इंटेलिजेंस।',
    viewInventory: 'इन्वेंटरी देखें',
    tonsMonth: 'टन / माह',
    countries: 'देश',
    qualityRate: 'गुणवत्ता दर',
    scrollExplore: 'एक्सप्लोर करने के लिए स्क्रॉल करें',

    // Stats
    statsTitle: 'बोलती संख्याएँ',
    statsSubtitle: 'हमारे उत्पादन मापदंड उत्कृष्टता की कहानी बताते हैं',
    dailyOutput: 'दैनिक उत्पादन',
    clientsServed: 'ग्राहक',
    exportCountries: 'निर्यात देश',
    yearsExperience: 'वर्ष अनुभव',
    ourImpact: 'हमारा प्रभाव',
    performance: 'प्रदर्शन',
    industryLeading: 'उद्योग में अग्रणी',
    statsDesc: 'बेजोड़ गुणवत्ता, निरंतरता और विश्वसनीयता के साथ विश्व स्तर पर प्रीमियम कॉयर उत्पादों का वितरण',
    tonsProducedMonthly: 'मासिक उत्पादित टन',
    highCapacityMfg: 'उच्च क्षमता वाला औद्योगिक विनिर्माण',
    globalCoverage: 'वैश्विक आपूर्ति श्रृंखला कवरेज',
    activeClients: 'सक्रिय ग्राहक',
    trustedPartnerships: 'विश्वसनीय व्यावसायिक भागीदारी',
    qualityAssurance: 'गुणवत्ता आश्वासन',
    isoCertified: 'आईएसओ-प्रमाणित निरीक्षण प्रक्रिया',

    // Manufacturing
    mfgTitle: 'विनिर्माण प्रक्रिया',
    mfgSubtitle: 'कच्चे नारियल के छिलके से लेकर प्रीमियम तैयार उत्पादों तक',

    // CTA
    ctaTitle: 'अपनी सप्लाई चेन बदलने के लिए तैयार?',
    ctaDesc: 'प्रीमियम गुणवत्ता वाले कॉयर उत्पादों और कुशल सप्लाई चेन प्रबंधन के लिए स्मार्ट कॉयर पर भरोसा करने वाले सैकड़ों व्यवसायों से जुड़ें।',
    ctaButton: 'अपनी यात्रा शुरू करें',
    whyChooseUs: 'हमें क्यों चुनें',
    futureCoirTitle: 'भविष्य',
    coirMfg: 'कॉयर विनिर्माण',
    ctaLeftDesc: 'हम प्रीमियम कॉयर उत्पादों को वितरित करने के लिए अत्याधुनिक तकनीक के साथ पारंपरिक शिल्प कौशल को जोड़ते हैं। हमारा स्मार्ट प्लेटफॉर्म आपको संपूर्ण विनिर्माण और आपूर्ति श्रृंखला प्रक्रिया पर पूर्ण दृश्यता प्रदान करता है।',
    startFreeTrial: 'मुफ्त परीक्षण शुरू करें',
    scheduleDemo: 'डेमो शेड्यूल करें',
    feat1Title: 'वास्तविक समय ट्रैकिंग',
    feat1Desc: 'लाइव डैशबोर्ड और त्वरित अलर्ट के साथ उत्पादन, इन्वेंटरी और डिलीवरी की निगरानी करें।',
    feat2Title: 'एआई-संचालित अंतर्दृष्टि',
    feat2Desc: 'स्मार्ट एनालिटिक्स मांग की भविष्यवाणी करते हैं, स्टॉक स्तरों को अनुकूलित करते हैं, और राजस्व वृद्धि को अधिकतम करते हैं।',
    feat3Title: 'आपूर्ति श्रृंखला नियंत्रण',
    feat3Desc: 'नारियल की भूसी के संग्रह से लेकर वैश्विक उत्पाद वितरण तक एंड-टू-एंड दृश्यता।',
    feat4Title: 'गुणवत्ता आश्वासन',
    feat4Desc: 'हर स्तर पर आईएसओ-प्रमाणित निरीक्षण प्रक्रिया निर्यात के लिए तैयार, प्रीमियम उत्पादों को सुनिश्चित करती है।',

    // Footer
    footerDesc: 'प्रीमियम कॉयर मैन्युफैक्चरिंग और सप्लाई चेन मैनेजमेंट प्लेटफॉर्म। नारियल फाइबर को टिकाऊ औद्योगिक उत्पादों में बदलना।',
    quickLinks: 'त्वरित लिंक',
    home: 'होम',
    about: 'हमारे बारे में',
    contact: 'संपर्क',
    contactInfo: 'संपर्क जानकारी',
    rights: 'सर्वाधिकार सुरक्षित।',
    products: 'उत्पाद',
    company: 'कंपनी',
    platform: 'प्लेटफॉर्म',
    support: 'सहायता',
    coirRope: 'कॉयर रस्सी',
    coirYarn: 'कॉयर यार्न',
    fiberBundles: 'फाइबर बंडल',
    rawFiber: 'कच्चा फाइबर',
    aboutUs: 'हमारे बारे में',
    manufacturing: 'विनिर्माण',
    qualityStandards: 'गुणवत्ता मानक',
    careers: 'करियर',
    inventorySystem: 'इन्वेंटरी सिस्टम',
    orderTracking: 'ऑर्डर ट्रैकिंग',
    contactUs: 'संपर्क करें',
    documentation: 'दस्तावेज़ीकरण',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    liveChat: 'लाइव चैट',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',

    langEn: 'English',
    langTa: 'தமிழ்',
    langHi: 'हिन्दी',

    // Auth
    signInPortal: 'साइन इन पोर्टल',
    selectRole: 'कृपया जारी रखने के लिए अपनी भूमिका का चयन करें',
    clientPortal: 'क्लाइंट पोर्टल',
    adminPanel: 'एडमिन पैनल',
    emailAddress: 'ईमेल पता',
    emailPlaceholder: 'name@company.com',
    password: 'पासवर्ड',
    passwordPlaceholder: '••••••••',
    forgotPassword: 'पासवर्ड भूल गए?',
    signInBtn: 'साइन इन करें',
    authenticating: 'सत्यापन किया जा रहा है...',
    dontHaveAccount: 'खाता नहीं है?',
    createOneNow: 'अभी एक खाता बनाएं',
    createAccountPortal: 'क्लाइंट खाता बनाएं',
    alreadyHaveAccount: 'पहले से ही एक खाता है?',
    backToLogin: 'यहाँ लॉग इन करें',
    registerBtn: 'कंपनी पंजीकृत करें',
    registering: 'पंजीकरण किया जा रहा है...',
    fullName: 'पूरा नाम',
    companyName: 'कंपनी का नाम',
    companyAddress: 'कंपनी का पता',
    phone: 'फ़ोन नंबर',
    step: 'चरण',
    personalDetails: 'व्यक्तिगत विवरण',
    companyDetails: 'कंपनी विवरण',
    continue: 'जारी रखें',
    buyCoir: 'कॉयर उत्पाद खरीदें',
    back: 'पीछे',

    // Sidebar & Menus
    dashboard: 'डैशबोर्ड',
    inventory: 'इन्वेंटरी',
    orders: 'मेरे ऑर्डर',
    chat: 'सहायता चैट',
    profile: 'प्रोफ़ाइल सेटिंग्स',
    contactAdmin: 'एडमिन से संपर्क करें',
    scanner: 'क्यूआर स्कैनर',
    workers: 'कर्मचारी निर्देशिका',
    suppliers: 'आपूर्तिकर्ता निर्देशिका',
    adminHome: 'एडमिन होम',
    manageProducts: 'उत्पाद प्रबंधन',
    clientOrders: 'क्लाइंट ऑर्डर',
    liveSupport: 'लाइव सहायता',
    systemStatus: 'लाइव सर्वर',
    notifications: 'सूचनाएं',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    noNotifications: 'कोई सूचना नहीं',
    signOut: 'साइन आउट',

    // Client Dashboard
    welcome: 'स्वागत है',
    repOf: 'प्रतिनिधि',
    manageCoirOrders: 'अपने इन्वेंटरी ऑर्डर प्रबंधित करें और शिपमेंट ट्रैक करें।',
    browseCatalog: 'कैटलॉग ब्राउज़ करें',
    orderHistory: 'ऑर्डर इतिहास',
    totalOrdersPlaced: 'कुल ऑर्डर',
    activeShipments: 'सक्रिय शिपमेंट',
    completedDeliveries: 'पूर्ण वितरण',
    totalInvestments: 'कुल निवेश',
    recentOrders: 'हाल के ऑर्डर',
    noOrders: 'कोई ऑर्डर नहीं मिला',
    viewAllOrders: 'सभी ऑर्डर देखें',
    orderId: 'ऑर्डर आईडी',
    date: 'दिनांक',
    total: 'कुल',
    status: 'स्थिति',
    actions: 'कार्रवाई',
    track: 'ट्रैक करें',

    // Client Inventory
    availableProducts: 'उपलब्ध कॉयर उत्पाद',
    searchPlaceholder: 'कॉयर उत्पाद खोजें...',
    stock: 'स्टॉक',
    price: 'कीमत',
    viewDetails: 'विवरण देखें',
    categories: 'श्रेणियां',

    // Client Products Detail
    productDetails: 'उत्पाद विवरण',
    specifications: 'विशिष्टता',
    pricePerTon: 'प्रति टन मूल्य',
    availableQty: 'उपलब्ध मात्रा',
    backToInventory: 'इन्वेंटरी पर वापस जाएं',
    placeOrder: 'ऑर्डर दें',
    orderEstimator: 'ऑर्डर अनुमानक और विशिष्टता विन्यास',
    fiberGrade: 'फाइबर ग्रेड',
    moistureLimit: 'नमी की सीमा',
    baleWeight: 'गांठ का वजन',
    quantityTons: 'मात्रा (टन)',
    estimatedPrice: 'अनुमानित मूल्य',
    taxFees: 'कर और शिपिंग शुल्क',
    grandTotal: 'कुल योग',
    submittingOrder: 'ऑर्डर जमा किया जा रहा है...',
    confirmOrder: 'ऑर्डर की पुष्टि करें',
    estimatedDelivery: 'अनुमानित वितरण',

    // Client Profile
    companyProfileSettings: 'कंपनी प्रोफ़ाइल सेटिंग्स',
    updateCompanyDetails: 'अपनी कंपनी की जानकारी अपडेट करें।',
    companyDetails: 'कंपनी विवरण',
    saveChanges: 'परिवर्तन सहेजें',
    saving: 'सहेजा जा रहा है...',

    // Client Contact
    contactOffice: 'कार्यालय संपर्क',
    sendInquiry: 'सहायता पूछताछ भेजें',
    subject: 'विषय',
    message: 'संदेश',
    sendBtn: 'संदेश भेजें',
    sending: 'भेजा जा रहा है...',
    contactDesc: 'थोक मूल्य निर्धारण या विशेष अनुरोधों के लिए हमारी टीम से संपर्क करें।',

    // Client Chat & Admin Chat
    chatSupport: 'चैट सहायता',
    typeMessage: 'संदेश टाइप करें...',
    send: 'भेजें',
    supportDesk: 'सहायता डेस्क',
    selectClient: 'चैटिंग शुरू करने के लिए क्लाइंट का चयन करें',

    // Admin Dashboard
    adminDashboard: 'एडमिन डैशबोर्ड',
    totalRevenue: 'कुल राजस्व',
    activeWorkers: 'सक्रिय कर्मचारी',
    supplierCount: 'आपूर्तिकर्ताओं की संख्या',
    analyticsChart: 'विश्लेषण चार्ट',
    recentSales: 'हाल की बिक्री',
    quickActions: 'त्वरित कार्रवाई',
    systemOverview: 'विनिर्माण और आपूर्ति श्रृंखला संचालन का वास्तविक समय अवलोकन।',

    // Admin Inventory
    coirProductsDb: 'कॉयर उत्पाद डेटाबेस',
    addProduct: 'नया उत्पाद जोड़ें',
    editProduct: 'उत्पाद संपादित करें',
    deleteProduct: 'उत्पाद हटाएं',
    prodName: 'उत्पाद का नाम',
    description: 'विवरण',
    imageUrl: 'छवि URL',
    stockTons: 'स्टॉक (टन)',
    pricePerTonRs: 'मूल्य प्रति टन (₹)',
    saveProduct: 'उत्पाद सहेजें',

    // Admin Orders
    manageClientOrders: 'क्लाइंट ऑर्डर प्रबंधित करें और शिपमेंट स्थिति अपडेट करें।',
    updateStatus: 'स्थिति अपडेट करें',
    currentStatus: 'वर्तमान स्थिति',

    // Admin Workers
    workersDirectory: 'कर्मचारी निर्देशिका',
    manageProductionWorkers: 'उत्पादन कर्मचारियों और पाली के समय को प्रबंधित करें।',
    addWorker: 'कर्मचारी जोड़ें',
    role: 'भूमिका',
    shift: 'पाली',

    // Admin Suppliers
    suppliersDirectory: 'आपूर्तिकर्ता निर्देशिका',
    manageRawSuppliers: 'कच्चे नारियल के छिलके और फाइबर आपूर्तिकर्ताओं को प्रबंधित करें।',
    addSupplier: 'आपूर्तिकर्ता जोड़ें',
    rawMaterial: 'कच्चा माल',
    contactNumber: 'संपर्क नंबर',

    // Admin Scanner
    qrScanner: 'क्यूआर कोड स्कैनर',
    scanBundleQR: 'कॉयर बंडल या ऑर्डर ट्रैकिंग क्यूआर कोड स्कैन करें।',
    bundlesScanned: 'स्कैन किए गए बंडल',
    activeScanner: 'सक्रिय स्कैनर',

    // AI Chatbot Widget
    aiAssistant: 'स्मार्ट कॉयर एआई सहायक',
    askAI: 'उत्पादों, ऑर्डरों या कॉयर विनिर्देशों के बारे में पूछें...',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    aiIntro: 'नमस्ते! मैं आपका स्मार्ट कॉयर एआई सहायक हूं। हमारे कॉयर उत्पादों, प्रसंस्करण चरणों, मूल्य निर्धारण या ऑर्डर रसद के बारे में कुछ भी पूछें।',
    online: 'ऑनलाइन',
    aiSug1: 'मूल्य और ग्रेड',
    aiSug1Q: 'कॉयर की गुणवत्ता ग्रेड और मूल्य निर्धारण क्या हैं?',
    aiSug2: 'विनिर्माण प्रक्रिया',
    aiSug2Q: 'औद्योगिक कॉयर फाइबर कैसे निकाला और संसाधित किया जाता है?',
    aiSug3: 'ऑर्डर और डिलीवरी',
    aiSug3Q: 'मैं अपने ऑर्डर कैसे दे सकता हूं और ट्रैक कर सकता हूं?',
    aiSug4: 'तकनीकी विनिर्देश',
    aiSug4Q: 'प्रीमियम निर्यात ग्रेड रस्सी के तकनीकी विनिर्देश क्या हैं?',

    // Additional keys
    loadingDashboard: 'आपका डैशबोर्ड लोड हो रहा है...',
    loadingRecentOrders: 'हाल के ऑर्डर लोड हो रहे हैं...',
    noOrdersFoundClickHere: 'कोई ऑर्डर नहीं मिला। उत्पादों को देखने और अपना पहला ऑर्डर देने के लिए यहाँ क्लिक करें।',
    orderRef: 'ऑर्डर संदर्भ',
    items: 'सामग्री',
    totalAmount: 'कुल राशि',
    productsUnit: 'उत्पाद',
    orderCoirProducts: '🟢 कॉयर उत्पाद ऑर्डर करें',
    updateCompanyProfile: '👤 कंपनी प्रोफ़ाइल अपडेट करें',
    supportInquiry: '✉️ सहायता और पूछताछ',
    needAssistance: 'सहायता की आवश्यकता है?',
    assistanceDesc: 'थोक मूल्य निर्धारण, कस्टम आयाम रस्सियों, या शिपिंग रसद विवरण के लिए सीधे हमारी टीम से संपर्क करें।',
    inquireNow: 'अभी पूछताछ करें',
    allCategories: 'सभी श्रेणियां',
    coirRopes: 'कॉयर रस्सियाँ',
    browseProductInventory: 'उत्पाद सूची ब्राउज़ करें',
    browseInventoryDesc: 'ऑर्डर देने के लिए हमारे टिकाऊ औद्योगिक नारियल फाइबर उत्पादों के कैटलॉग से वस्तुओं का चयन करें।',
    loadingCatalog: 'उत्पाद कैटलॉग लोड हो रहा है...',
    noProductsMatch: 'आपके फ़िल्टर से कोई उत्पाद मेल नहीं खाता। अपनी खोज साफ़ करने या कोई अन्य श्रेणी चुनने का प्रयास करें।',
    ton: 'टन',
    loadingSpecs: 'विनिर्देश लोड हो रहे हैं...',
    couldNotLoadDetails: 'उत्पाद विवरण लोड नहीं किया जा सका।',
    grade: 'ग्रेड',
    technicalSpecifications: 'तकनीकी विनिर्देश',
    fiberComposition: 'फाइबर संरचना',
    yarnRopeColor: 'यार्न/रस्सी का रंग',
    moistureLevel: 'नमी का स्तर',
    tensileStrength: 'तन्यता मजबूती',
    lengthPerUnit: 'प्रति यूनिट लंबाई',
    thicknessDiameter: 'मोटाई / व्यास',
    qrCodeInventoryTag: 'क्यूआर कोड इन्वेंटरी टैग',
    qrVerifyDesc: 'उत्पाद विनिर्देशों, गोदाम SKU कोड और लाइव मूल्य निर्धारण को तुरंत सत्यापित करने के लिए इस क्यूआर कोड को स्कैन करें।',
    orderRequestPlaced: 'ऑर्डर अनुरोध सबमिट किया गया!',
    orderSuccessDesc: 'आपका ऑर्डर सफलतापूर्वक दर्ज कर लिया गया है। अब आपको आपके ऑर्डर ट्रैकिंग पोर्टल पर पुनर्निर्देशित किया जा रहा है...',
    placeOrderRequest: 'ऑर्डर अनुरोध भेजें',
    provideAddress: 'कृपया शिपिंग डिलीवरी का पता प्रदान करें।',
    rate: 'दर',
    shippingDeliveryAddress: 'शिपिंग डिलीवरी का पता',
    addressPlaceholder: 'पिन कोड के साथ पूरा शिपिंग पता दर्ज करें...',
    preferredPaymentMethod: 'पसंदीदा भुगतान विधि',
    bankTransferOption: 'बैंक वायर ट्रांसफर (थोक)',
    lcOption: 'एल/सी (ऋण पत्र - निर्यात)',
    net30Option: 'नेट 30 खाता (स्वीकृत कॉर्पोरेट)',
    orderNotesOptional: 'ऑर्डर नोट्स (वैकल्पिक)',
    notesPlaceholder: 'जैसे कस्टम पैकेजिंग आवश्यकताएं, डिलीवरी का समय',
    subtotal: 'उपयोग',
    estimatedGst: 'अनुमानित जीएसटी (18%)',
    shippingLogistics: 'शिपिंग / रसद',
    free: 'मुफ़्त',
    estimatedTotal: 'अनुमानित कुल',
    submittingOrderRequest: 'ऑर्डर अनुरोध सबमिट किया गया...',
    statusPending: 'लंबित',
    statusConfirmed: 'पुष्टि की गई',
    statusProcessing: 'प्रसंस्करण',
    statusShipped: 'भेजा गया',
    statusDelivered: 'वितरित',
    profileSettingsDesc: 'अपने व्यक्तिगत, कॉर्पोरेट और डिफ़ॉल्ट वितरण पते के विवरण अपडेट करें।',
    profileUpdatedSuccess: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    profileUpdatedError: 'प्रोफ़ाइल अपडेट करने में विफल। कृपया पुन: प्रयास करें।',
    companyContactInfo: 'कंपनी और संपर्क जानकारी',
    contactPhone: 'संपर्क फ़ोन',
    defaultCorporateAddress: 'डिफ़ॉल्ट कॉर्पोरेट वितरण पता',
    streetAddress: 'गली का पता',
    streetPlaceholder: 'जैसे 100 मेन सेंट, सुइट 400',
    city: 'शहर',
    stateProvince: 'राज्य / प्रांत',
    country: 'देश',
    zipPostalCode: 'पिन कोड',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    contactAdminDesc: 'हमारे कारखाने व्यवस्थापक, रसद समन्वयकों, या थोक सहायता टीम से संपर्क करें।',
    fillSubjectMessage: 'कृपया विषय और संदेश दोनों भरें।',
    inquirySubmittedSuccess: 'आपकी सहायता पूछताछ सबमिट कर दी गई है! हमारी टीम शीघ्र ही आपसे संपर्क करेगी।',
    inquirySubmittedError: 'पूछताछ सबमिट करने में विफल। कृपया पुन: प्रयास करें।',
    factoryHeadquarters: 'कारखाना मुख्यालय',
    address: 'पता',
    wholesaleHelpline: 'थोक हेल्पलाइन',
    emailSupport: 'ई-मेल सहायता',
    directBulkInquiries: 'प्रत्यक्ष थोक पूछताछ',
    bulkInquiryDesc: 'प्रति माह 10 टन से अधिक शिपमेंट, कस्टम रंग यार्न मिश्रण, या विशिष्ट फाइबर तन्यता ताकत प्रमाणपत्रों के लिए, कृपया अपनी विशिष्टताओं को निर्दिष्ट करते हुए एक औपचारिक पूछताछ फॉर्म जमा करें।',
    submitSupportInquiry: 'सहायता पूछताछ सबमिट करें',
    subject: 'विषय',
    subjectPlaceholder: 'जैसे कस्टम रस्सी की मोटाई के बारे में पूछताछ',
    message: 'संदेश',
    messagePlaceholder: 'अपने प्रश्नों या ऑर्डर अनुरोधों का विवरण यहाँ दें...',
    sendInquiryBtn: 'पूछताछ भेजें',
    submittingInquiry: 'पूछताछ सबमिट की जा रही है...',
    liveSupportDesk: 'लाइव सहायता डेस्क',
    liveSupportDesc: 'आपूर्ति श्रृंखला प्रश्नों या आदेशों के लिए हमारे परिचालन नियंत्रण कक्ष के साथ वास्तविक समय में चैट करें।',
    supportOperators: 'सहायता ऑपरेटर',
    loadingSupportDesk: 'सहायता डेस्क लोड हो रहा है...',
    noOperatorsOnline: 'कोई ऑपरेटर ऑनलाइन नहीं है। कृपया एडमिन से संपर्क करें के माध्यम से सहायता पूछताछ छोड़ें।',
    operationsAgent: 'संचालन एजेंट',
    loadingMessages: 'संदेश इतिहास लोड हो रहा है...',
    welcomeChatWith: '👋 स्वागत है! चैट शुरू करने के लिए एक संदेश भेजें',
    isTypingText: 'टाइप कर रहा है...',
    selectAgentChat: 'चैट शुरू करने के लिए बाईं ओर से एक सहायता एजेंट का चयन करें',
    opsDashboardTitle: 'संचालन नियंत्रण डैशबोर्ड',
    opsDashboardDesc: 'वास्तविक समय कॉयर विनिर्माण मेट्रिक्स, इन्वेंट्री रिजर्व और सक्रिय क्लाइंट लॉजिस्टिक्स ऑर्डर।',
    addProductBtn: '➕ उत्पाद जोड़ें',
    viewCatalogBtn: '🛠️ कैटलॉग देखें',
    factorySalesRevenue: 'फैक्ट्री बिक्री राजस्व',
    receivedOrders: 'प्राप्त ऑर्डर',
    registeredClients: 'पंजीकृत ग्राहक',
    lowStockItems: 'कम स्टॉक वाली वस्तुएं',
    incomingClientOrders: 'आने वाले क्लाइंट ऑर्डर',
    processOrdersBtn: 'ऑर्डर प्रोसेस करें →',
    loadingOpsLogs: 'परिचालन लॉग लोड हो रहे हैं...',
    noOrdersReceived: 'अभी तक कोई ऑर्डर प्राप्त नहीं हुआ है। सक्रिय ग्राहक पोर्टल यहाँ ऑर्डर प्रदर्शित करेंगे।',
    orderTableHead: 'ऑर्डर',
    clientCompanyTableHead: 'ग्राहक / कंपनी',
    grandTotalTableHead: 'कुल योग',
    logDateTableHead: 'लॉग दिनांक',
    prodCatalogStockLevels: 'उत्पाद कैटलॉग और स्टॉक स्तर',
    stockQuantityTableHead: 'स्टॉक मात्रा',
    outOfStock: 'स्टॉक में नहीं है',
    lowStockStatus: 'कम स्टॉक',
    inStockStatus: 'स्टॉक में है',
    deleteBtn: '🗑️ हटाएं',
    logisticsControl: 'रसद नियंत्रण',
    trackActiveShipments: '🚛 सक्रिय शिपमेंट ट्रैक करें',
    manageWorkerLogs: '👷 कर्मचारी लॉग प्रबंधित करें',
    aiBusinessInsights: '🔮 एआई बिजनेस इनसाइट्स',
    analyzingTrends: 'बिक्री और स्टॉक प्रवृत्तियों का विश्लेषण किया जा रहा है...',
    noInsightsYet: 'अभी तक कोई अंतर्दृष्टि उत्पन्न नहीं हुई है।',
    systemAlert: 'सिस्टम अलर्ट',
    systemAlertDesc: 'मांग पूर्वानुमान सटीकता के लिए दैनिक उत्पादन मेट्रिक्स और कच्चे नारियल की भूसी की आपूर्ति नियमित रूप से अपडेट करना सुनिश्चित करें।',
    adjustStockLevel: 'स्टॉक स्तर समायोजित करें',
    productLabel: 'उत्पाद:',
    qtyInStockKg: 'स्टॉक में मात्रा (किग्रा)',
    cancelBtn: 'रद्द करें',
    saveChangesBtn: 'परिवर्तन सहेजें',
    createNewProductStockEntry: 'नया उत्पाद और स्टॉक प्रविष्टि बनाएं',
    registerProductDesc: 'कॉयर कैटलॉग में एक नया उत्पाद पंजीकृत करें और उसके गोदाम स्टॉक स्तरों को प्रारंभ करें।',
    skuLabel: 'SKU (स्टॉक कीपिंग यूनिट)',
    qualityGradeLabel: 'गुणवत्ता ग्रेड',
    priceInrPerKg: 'कीमत (INR प्रति किग्रा)',
    unitPackagingWeightKg: 'यूनिट पैकेजिंग वजन (किग्रा)',
    initialStockQtyKg: 'प्रारंभिक स्टॉक मात्रा (किग्रा)',
    minStockAlertLimitKg: 'न्यूनतम स्टॉक चेतावनी सीमा (किग्रा)',
    prodInventoryReserves: 'उत्पाद इन्वेंटरी रिजर्व',
    manageCatalogStockDesc: 'फैक्ट्री उत्पाद कैटलॉग प्रबंधित करें और गोदाम स्टॉक स्तर देखें।',
    totalCatalogProducts: 'कुल कैटलॉग उत्पाद',
    totalInStock: 'कुल स्टॉक में',
    lowStockWarnings: 'कम स्टॉक चेतावनी',
    outOfStockItems: 'स्टॉक से बाहर की वस्तुएं',
    warehouseStockLevels: 'गोदाम स्टॉक स्तर',
    loadingStockDetails: 'स्टॉक विवरण लोड हो रहा है...',
    noInventoryFound: 'कोई इन्वेंटरी नहीं मिली। सिस्टम को आबाद करने के लिए "नया उत्पाद जोड़ें" पर क्लिक करें।',
    warehouseTableHead: 'गोदाम',
    createSeedProductBtn: 'उत्पाद बनाएं और बीज डालें',
    registeringProduct: 'उत्पाद पंजीकृत किया जा रहा है...',
    logisticsClientPurchases: 'रसद और ग्राहक खरीद',
    opsOrdersDesc: 'थोक कॉयर ऑर्डर अनुरोधों को संसाधित करें, ट्रैक नंबरों को अपडेट करें और भुगतानों को प्रबंधित करें।',
    incomingOrdersTitle: 'आने वाले ऑर्डर',
    noOrdersInSystem: 'सिस्टम में कोई ऑर्डर प्राप्त नहीं हुआ है।',
    directClient: 'प्रत्यक्ष ग्राहक',
    paidStatus: 'भुगतान किया गया',
    unpaidStatus: 'भुगतान नहीं किया गया',
    processOrderTitle: 'ऑर्डर प्रोसेस करें',
    clientLabel: 'ग्राहक:',
    workflowStatusActions: 'कार्यप्रवाह स्थिति क्रियाएं',
    confirmOrderBtn: 'ऑर्डर की पुष्टि करें',
    beginProcessingBtn: '⚙️ प्रसंस्करण शुरू करें',
    shipBtn: 'शिप करें (विवरण दर्ज करें)',
    markDeliveredBtn: 'वितरित चिह्नित करें',
    billingPaymentStatus: 'बिलिंग और भुगतान स्थिति',
    paymentStatusLabel: 'भुगतान स्थिति:',
    approvePaymentBtn: 'भुगतान स्वीकृत करें',
    resetUnpaidBtn: 'अवैतनिक रीसेट करें',
    deliveryAddress: 'वितरण का पता',
    purchasedItems: 'खरीदी गई वस्तुएं',
    quantityLabel: 'मात्रा:',
    selectOrderProcessDesc: 'शिपमेंट रसद को संसाधित करने और बिलिंग प्रबंधित करने के लिए सूची से एक ऑर्डर चुनें।',
    enterShippingDetailsTitle: 'शिपिंग रसद विवरण दर्ज करें',
    logisticsCarrierLabel: 'रसद वाहक',
    trackingNumberLabel: 'ट्रैकिंग नंबर',
    estimatedDeliveryDateLabel: 'अनुमानित डिलीवरी की तारीख',
    dispatchOrderBtn: 'ऑर्डर भेजें',
    workersDirectoryDesc: 'कर्मचारी लॉग, विभाग के कार्यों और सक्रिय कारखाने की पारियों की निगरानी करें।',
    shiftOpsLabel: 'शिफ्ट संचालन (चरण 4 WIP)',
    activeStatus: 'सक्रिय',
    onLeaveStatus: 'छुट्टी पर',
    machineOperator: 'मशीन ऑपरेटर',
    qualityAuditor: 'गुणवत्ता लेखापरीक्षक',
    logisticsHandler: 'रसद संचालक',
    decorticationUnit: 'डेकोर्टिकेशन इकाई',
    inspectionDept: 'निरीक्षण विभाग',
    warehouseA: 'गोदाम A',
    suppliersDirectoryDesc: 'कॉयर सामग्री कच्चे माल की आपूर्ति विक्रेताओं और गुणवत्ता प्रदर्शन स्कोर की निगरानी करें।',
    supplyChainVendorsLabel: 'आपूर्ति श्रृंखला विक्रेता (चरण 4 WIP)',
    contactColon: 'संपर्क:',
    suppliesColon: 'आपूर्ति:',
    rawCoconutHusks: 'कच्चे नारियल के छिलके',
    decorticatedGreenHusks: 'डेकोर्टिकेटेड हरे छिलके',
    scannerDesc: 'उत्पाद विवरणों को तुरंत देखने और इन्वेंट्री स्टॉक को समायोजित करने के लिए क्यूआर कोड स्कैन या अपलोड करें।',
    scanInputTitle: 'Scan Input स्कैन इनपुट',
    scanPromptDesc: 'क्यूआर कोड छवि अपलोड करें, कैमरे का उपयोग करें, या सिमुलेटेड स्कैन चलाएं',
    scanningProductTag: 'उत्पाद टैग स्कैन किया जा रहा है...',
    uploadQrImageBtn: '📁 क्यूआर छवि अपलोड करें',
    stopCameraBtn: '⏹ कैमरा रोकें',
    liveCameraBtn: '📷 लाइव कैमरा',
    demoScanBtn: '🎯 डेमो स्कैन',
    recentScansTitle: 'हाल के स्कैन',
    scanResultTitle: 'स्कैन परिणाम',
    demoDataBadge: 'डेमो डेटा',
    weightLabel: 'वजन',
    currentStockLabel: 'वर्तमान स्टॉक',
    stockAdjustmentTitle: '📦 स्टॉक समायोजन',
    addStockBtn: '+ स्टॉक जोड़ें',
    removeStockBtn: '− स्टॉक हटाएं',
    adjustmentNoteLabel: 'समायोजन नोट (वैकल्पिक)',
    adjustmentNotePlaceholder: 'जैसे, आने वाला शिपमेंट, क्षतिग्रस्त सामान...',
    addStockSubmit: '+ जोड़ें',
    removeStockSubmit: '− घटाएं',
    units: 'इकाइयाँ',
    noProductScanned: 'कोई उत्पाद स्कैन नहीं हुआ',
    noProductScannedDesc: 'गोदाम स्कैन का अनुकरण करने के लिए क्यूआर कोड छवि अपलोड करें, अपने डिवाइस कैमरे का उपयोग करें, या "ऑर्डर स्कैन" पर क्लिक करें।',
    opsSupportDesk: 'संचालन सहायता डेस्क',
    opsChatDesc: 'आपूर्ति श्रृंखला अनुरोधों को हल करें और पंजीकृत कारखाने खरीदारों के साथ वास्तविक समय में चैट करें।',
    activeChatsTab: 'सक्रिय चैट',
    clientContactsTab: 'ग्राहक संपर्क',
    loadingChatThreads: 'चैट थ्रेड्स लोड हो रहे हैं...',
    noActiveChatsDesc: 'कोई सक्रिय सहायता थ्रेड नहीं है। एक बार जब ग्राहक लाइव चैट सत्र शुरू करेंगे तो वे यहाँ प्रदर्शित होंगे।',
    unknownClient: 'अज्ञान ग्राहक',
    noMessagesYet: 'अभी तक कोई संदेश नहीं',
    loadingClientsList: 'ग्राहक सूची लोड हो रही है...',
    noBuyersRegistered: 'डेटाबेस में कोई खरीदार पंजीकृत नहीं है।',
    buyerRepFrom: 'क्रेता प्रतिनिधि',
    loadingMessageLogs: 'संदेश लॉग लोड हो रहे हैं...',
    noMessagesThread: 'इस चैट थ्रेड में कोई संदेश नहीं है। सहायता सत्र शुरू करने के लिए नीचे टाइप करें।',
    typeSupportReplyPlaceholder: 'सहायता उत्तर टाइप करें...',
    replyBtn: 'उत्तर दें',
    selectBuyerThreadDesc: 'सहायता चैट शुरू करने के लिए एक सक्रिय खरीदार थ्रेड चुनें या किसी ग्राहक को खोजें',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  useEffect(() => {
    const saved = localStorage.getItem('coir-lang');
    if (saved && translations[saved]) setLang(saved);
  }, []);

  useEffect(() => {
    localStorage.setItem('coir-lang', lang);
  }, [lang]);

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
